Search.appendIndex(
    [
                {
            "fqsen": "\\josemmo\\Verifactu\\Exceptions\\AeatException",
            "name": "AeatException",
            "summary": "Exception\u0020thrown\u0020by\u0020the\u0020AEAT\u0020client",
            "url": "classes/josemmo-Verifactu-Exceptions-AeatException.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Exceptions\\InvalidModelException",
            "name": "InvalidModelException",
            "summary": "Exception\u0020thrown\u0020when\u0020a\u0020model\u0020class\u0020does\u0020not\u0020pass\u0020validation",
            "url": "classes/josemmo-Verifactu-Exceptions-InvalidModelException.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Exceptions\\InvalidModelException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor",
            "url": "classes/josemmo-Verifactu-Exceptions-InvalidModelException.html#method___construct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Exceptions\\InvalidModelException\u003A\u003A\u0024violations",
            "name": "violations",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Exceptions-InvalidModelException.html#property_violations"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem",
            "name": "ComputerSystem",
            "summary": "Computer\u0020system",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024vendorName",
            "name": "vendorName",
            "summary": "Nombre\u002Draz\u00F3n\u0020social\u0020de\u0020la\u0020persona\u0020o\u0020entidad\u0020productora",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_vendorName"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024vendorNif",
            "name": "vendorNif",
            "summary": "NIF\u0020de\u0020la\u0020persona\u0020o\u0020entidad\u0020productora",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_vendorNif"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Nombre\u0020dado\u0020por\u0020la\u0020persona\u0020o\u0020entidad\u0020productora\u0020a\u0020su\u0020sistema\u0020inform\u00E1tico\u0020de\u0020facturaci\u00F3n\u0020\u0028SIF\u0029",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_name"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024id",
            "name": "id",
            "summary": "C\u00F3digo\u0020identificativo\u0020dado\u0020por\u0020la\u0020persona\u0020o\u0020entidad\u0020productora\u0020a\u0020su\u0020sistema\u0020inform\u00E1tico\u0020de\u0020facturaci\u00F3n\u0020\u0028SIF\u0029",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_id"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024version",
            "name": "version",
            "summary": "Identificaci\u00F3n\u0020de\u0020la\u0020versi\u00F3n\u0020del\u0020sistema\u0020inform\u00E1tico\u0020de\u0020facturaci\u00F3n\u0020\u0028SIF\u0029",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_version"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024installationNumber",
            "name": "installationNumber",
            "summary": "N\u00FAmero\u0020de\u0020instalaci\u00F3n\u0020del\u0020sistema\u0020inform\u00E1tico\u0020de\u0020facturaci\u00F3n\u0020\u0028SIF\u0029\u0020utilizado",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_installationNumber"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024onlySupportsVerifactu",
            "name": "onlySupportsVerifactu",
            "summary": "Especifica\u0020si\u0020solo\u0020puede\u0020funcionar\u0020como\u0020\u0022VERI\u002AFACTU\u0022\u0020o\u0020tambi\u00E9n\u0020puede\u0020funcionar\u0020como\u0020\u0022no\u0020VERI\u002AFACTU\u0022\u0020\u0028offline\u0029",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_onlySupportsVerifactu"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024supportsMultipleTaxpayers",
            "name": "supportsMultipleTaxpayers",
            "summary": "Especifica\u0020si\u0020permite\u0020llevar\u0020independientemente\u0020la\u0020facturaci\u00F3n\u0020de\u0020varios\u0020obligados\u0020tributarios",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_supportsMultipleTaxpayers"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\ComputerSystem\u003A\u003A\u0024hasMultipleTaxpayers",
            "name": "hasMultipleTaxpayers",
            "summary": "En\u0020el\u0020momento\u0020de\u0020la\u0020generaci\u00F3n\u0020de\u0020este\u0020registro,\u0020est\u00E1\u0020soportando\u0020la\u0020facturaci\u00F3n\u0020de\u0020m\u00E1s\u0020de\u0020un\u0020obligado\u0020tributario",
            "url": "classes/josemmo-Verifactu-Models-ComputerSystem.html#property_hasMultipleTaxpayers"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Model",
            "name": "Model",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Model.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Model\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020this\u0020instance",
            "url": "classes/josemmo-Verifactu-Models-Model.html#method_validate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails",
            "name": "BreakdownDetails",
            "summary": "Detalle\u0020de\u0020desglose",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003AvalidateRegimeType\u0028\u0029",
            "name": "validateRegimeType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#method_validateRegimeType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003AvalidateOperationType\u0028\u0029",
            "name": "validateOperationType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#method_validateOperationType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003AvalidateTaxAmount\u0028\u0029",
            "name": "validateTaxAmount",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#method_validateTaxAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003AvalidateSurchargeAmount\u0028\u0029",
            "name": "validateSurchargeAmount",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#method_validateSurchargeAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024taxType",
            "name": "taxType",
            "summary": "Impuesto\u0020de\u0020aplicaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_taxType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024regimeType",
            "name": "regimeType",
            "summary": "Clave\u0020que\u0020identifica\u0020el\u0020tipo\u0020de\u0020r\u00E9gimen\u0020del\u0020impuesto\u0020o\u0020una\u0020operaci\u00F3n\u0020con\u0020trascendencia\u0020tributaria",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_regimeType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024operationType",
            "name": "operationType",
            "summary": "Clave\u0020de\u0020la\u0020operaci\u00F3n\u0020sujeta\u0020y\u0020no\u0020exenta,\u0020clave\u0020de\u0020la\u0020operaci\u00F3n\u0020no\u0020sujeta,\u0020o\u0020causa\u0020de\u0020la\u0020exenci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_operationType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024baseAmount",
            "name": "baseAmount",
            "summary": "Magnitud\u0020dineraria\u0020sobre\u0020la\u0020que\u0020se\u0020aplica\u0020el\u0020tipo\u0020impositivo\u0020\/\u0020Importe\u0020no\u0020sujeto",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_baseAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024taxRate",
            "name": "taxRate",
            "summary": "Porcentaje\u0020aplicado\u0020sobre\u0020la\u0020base\u0020imponible\u0020para\u0020calcular\u0020la\u0020cuota",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_taxRate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024taxAmount",
            "name": "taxAmount",
            "summary": "Cuota\u0020resultante\u0020de\u0020aplicar\u0020a\u0020la\u0020base\u0020imponible\u0020el\u0020tipo\u0020impositivo",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_taxAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024surchargeRate",
            "name": "surchargeRate",
            "summary": "Porcentaje\u0020aplicado\u0020sobre\u0020la\u0020base\u0020imponible\u0020para\u0020calcular\u0020la\u0020cuota",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_surchargeRate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\BreakdownDetails\u003A\u003A\u0024surchargeAmount",
            "name": "surchargeAmount",
            "summary": "Cuota\u0020resultante\u0020de\u0020aplicar\u0020a\u0020la\u0020base\u0020imponible\u0020el\u0020tipo\u0020de\u0020recargo\u0020de\u0020equivalencia",
            "url": "classes/josemmo-Verifactu-Models-Records-BreakdownDetails.html#property_surchargeAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CancellationRecord",
            "name": "CancellationRecord",
            "summary": "Registro\u0020de\u0020anulaci\u00F3n\u0020de\u0020una\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-CancellationRecord.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CancellationRecord\u003A\u003AcalculateHash\u0028\u0029",
            "name": "calculateHash",
            "summary": "Calculate\u0020record\u0020hash",
            "url": "classes/josemmo-Verifactu-Models-Records-CancellationRecord.html#method_calculateHash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CancellationRecord\u003A\u003AvalidateEnforcePreviousInvoice\u0028\u0029",
            "name": "validateEnforcePreviousInvoice",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-CancellationRecord.html#method_validateEnforcePreviousInvoice"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CancellationRecord\u003A\u003A\u0024withoutPriorRecord",
            "name": "withoutPriorRecord",
            "summary": "Indicador\u0020que\u0020especifica\u0020que\u0020se\u0020trata\u0020de\u0020la\u0020anulaci\u00F3n\u0020de\u0020un\u0020registro\u0020que\u0020no\u0020existe\u0020en\u0020la\u0020AEAT\u0020o\u0020en\u0020el\u0020SIF.",
            "url": "classes/josemmo-Verifactu-Models-Records-CancellationRecord.html#property_withoutPriorRecord"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CorrectiveType",
            "name": "CorrectiveType",
            "summary": "Tipo\u0020de\u0020factura\u0020rectificativa",
            "url": "classes/josemmo-Verifactu-Models-Records-CorrectiveType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CorrectiveType\u003A\u003ASubstitution",
            "name": "Substitution",
            "summary": "Por\u0020sustituci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-CorrectiveType.html#enumcase_Substitution"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\CorrectiveType\u003A\u003ADifferences",
            "name": "Differences",
            "summary": "Por\u0020diferencias",
            "url": "classes/josemmo-Verifactu-Models-Records-CorrectiveType.html#enumcase_Differences"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\FiscalIdentifier",
            "name": "FiscalIdentifier",
            "summary": "Identificador\u0020fiscal",
            "url": "classes/josemmo-Verifactu-Models-Records-FiscalIdentifier.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\FiscalIdentifier\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor",
            "url": "classes/josemmo-Verifactu-Models-Records-FiscalIdentifier.html#method___construct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\FiscalIdentifier\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Nombre\u002Draz\u00F3n\u0020social",
            "url": "classes/josemmo-Verifactu-Models-Records-FiscalIdentifier.html#property_name"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\FiscalIdentifier\u003A\u003A\u0024nif",
            "name": "nif",
            "summary": "N\u00FAmero\u0020de\u0020identificaci\u00F3n\u0020fiscal\u0020\u0028NIF\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-FiscalIdentifier.html#property_nif"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier",
            "name": "ForeignFiscalIdentifier",
            "summary": "Identificador\u0020fiscal\u0020de\u0020fuera\u0020de\u0020Espa\u00F1a",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003AvalidateVatNumber\u0028\u0029",
            "name": "validateVatNumber",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#method_validateVatNumber"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003AvalidateType\u0028\u0029",
            "name": "validateType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#method_validateType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003AvalidateCountry\u0028\u0029",
            "name": "validateCountry",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#method_validateCountry"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Nombre\u002Draz\u00F3n\u0020social",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#property_name"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003A\u0024country",
            "name": "country",
            "summary": "C\u00F3digo\u0020del\u0020pa\u00EDs\u0020\u0028ISO\u00203166\u002D1\u0020alpha\u002D2\u0020codes\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#property_country"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003A\u0024type",
            "name": "type",
            "summary": "Clave\u0020para\u0020establecer\u0020el\u0020tipo\u0020de\u0020identificaci\u00F3n\u0020en\u0020el\u0020pa\u00EDs\u0020de\u0020residencia",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#property_type"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignFiscalIdentifier\u003A\u003A\u0024value",
            "name": "value",
            "summary": "N\u00FAmero\u0020de\u0020identificaci\u00F3n\u0020en\u0020el\u0020pa\u00EDs\u0020de\u0020residencia",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignFiscalIdentifier.html#property_value"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType",
            "name": "ForeignIdType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003AVAT",
            "name": "VAT",
            "summary": "NIF\u002DIVA",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_VAT"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003APassport",
            "name": "Passport",
            "summary": "Pasaporte",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_Passport"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003ANationalId",
            "name": "NationalId",
            "summary": "Documento\u0020oficial\u0020de\u0020identificaci\u00F3n\u0020expedido\u0020por\u0020el\u0020pa\u00EDs\u0020o\u0020territorio\u0020de\u0020residencia",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_NationalId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003AResidence",
            "name": "Residence",
            "summary": "Certificado\u0020de\u0020residencia",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_Residence"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003AOther",
            "name": "Other",
            "summary": "Otro\u0020documento\u0020probatorio",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_Other"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\ForeignIdType\u003A\u003AUnregistered",
            "name": "Unregistered",
            "summary": "No\u0020censado\u0020\u0028en\u0020caso\u0020de\u0020que\u0020todav\u00EDa\u0020no\u0020est\u00E9\u0020dado\u0020de\u0020alta\u0020en\u0020la\u0020AEAT\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-ForeignIdType.html#enumcase_Unregistered"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier",
            "name": "InvoiceIdentifier",
            "summary": "Identificador\u0020de\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html#method___construct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "Compare\u0020instance\u0020against\u0020another\u0020invoice\u0020identifier",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html#method_equals"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier\u003A\u003A\u0024issuerId",
            "name": "issuerId",
            "summary": "N\u00FAmero\u0020de\u0020identificaci\u00F3n\u0020fiscal\u0020\u0028NIF\u0029\u0020del\u0020obligado\u0020a\u0020expedir\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html#property_issuerId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier\u003A\u003A\u0024invoiceNumber",
            "name": "invoiceNumber",
            "summary": "N\u00BA\u0020Serie\u0020\u002B\u0020N\u00BA\u0020Factura\u0020que\u0020identifica\u0020a\u0020la\u0020factura\u0020emitida",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html#property_invoiceNumber"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceIdentifier\u003A\u003A\u0024issueDate",
            "name": "issueDate",
            "summary": "Fecha\u0020de\u0020expedici\u00F3n\u0020de\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceIdentifier.html#property_issueDate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType",
            "name": "InvoiceType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AFactura",
            "name": "Factura",
            "summary": "Factura\u0020\u0028Art.\u00206,\u00207.2\u0020y\u00207.3\u0020del\u0020R.D.\u00201619\/2012\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_Factura"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003ASimplificada",
            "name": "Simplificada",
            "summary": "Factura\u0020simplificada\u0020y\u0020facturas\u0020sin\u0020identificaci\u00F3n\u0020del\u0020destinatario\u0020\u0028Art.\u00206.1.D\u0020del\u0020R.D.\u00201619\/2012\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_Simplificada"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003ASustitutiva",
            "name": "Sustitutiva",
            "summary": "Factura\u0020emitida\u0020en\u0020sustituci\u00F3n\u0020de\u0020facturas\u0020simplificadas\u0020facturadas\u0020y\u0020declaradas",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_Sustitutiva"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AR1",
            "name": "R1",
            "summary": "Factura\u0020rectificativa\u0020\u0028Art\u002080.1\u0020y\u002080.2\u0020y\u0020error\u0020fundado\u0020en\u0020derecho\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_R1"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AR2",
            "name": "R2",
            "summary": "Factura\u0020rectificativa\u0020\u0028Art.\u002080.3\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_R2"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AR3",
            "name": "R3",
            "summary": "Factura\u0020rectificativa\u0020\u0028Art.\u002080.4\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_R3"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AR4",
            "name": "R4",
            "summary": "Factura\u0020rectificativa\u0020\u0028Resto\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_R4"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\InvoiceType\u003A\u003AR5",
            "name": "R5",
            "summary": "Factura\u0020rectificativa\u0020en\u0020facturas\u0020simplificadas",
            "url": "classes/josemmo-Verifactu-Models-Records-InvoiceType.html#enumcase_R5"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType",
            "name": "OperationType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AisSubject\u0028\u0029",
            "name": "isSubject",
            "summary": "Is\u0020subject\u0020operation",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#method_isSubject"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AisNonSubject\u0028\u0029",
            "name": "isNonSubject",
            "summary": "Is\u0020non\u002Dsubject\u0020operation",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#method_isNonSubject"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AisExempt\u0028\u0029",
            "name": "isExempt",
            "summary": "Is\u0020exempt\u0020operation",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#method_isExempt"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003ASubject",
            "name": "Subject",
            "summary": "Operaci\u00F3n\u0020sujeta\u0020y\u0020no\u0020exenta\u0020\u002D\u0020Sin\u0020inversi\u00F3n\u0020del\u0020sujeto\u0020pasivo",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_Subject"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003APassiveSubject",
            "name": "PassiveSubject",
            "summary": "Operaci\u00F3n\u0020sujeta\u0020y\u0020no\u0020exenta\u0020\u002D\u0020Con\u0020inversi\u00F3n\u0020del\u0020sujeto\u0020pasivo",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_PassiveSubject"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003ANonSubject",
            "name": "NonSubject",
            "summary": "Operaci\u00F3n\u0020no\u0020sujeta\u0020\u002D\u0020Art\u00EDculos\u00207,\u002014\u0020y\u0020otros",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_NonSubject"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003ANonSubjectByLocation",
            "name": "NonSubjectByLocation",
            "summary": "Operaci\u00F3n\u0020no\u0020sujeta\u0020por\u0020reglas\u0020de\u0020localizaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_NonSubjectByLocation"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByArticle20",
            "name": "ExemptByArticle20",
            "summary": "Exenta\u0020por\u0020el\u0020art\u00EDculo\u002020",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByArticle20"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByArticle21",
            "name": "ExemptByArticle21",
            "summary": "Exenta\u0020por\u0020el\u0020art\u00EDculo\u002021",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByArticle21"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByArticle22",
            "name": "ExemptByArticle22",
            "summary": "Exenta\u0020por\u0020el\u0020art\u00EDculo\u002022",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByArticle22"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByArticles23And24",
            "name": "ExemptByArticles23And24",
            "summary": "Exenta\u0020por\u0020los\u0020art\u00EDculos\u002023\u0020y\u002024",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByArticles23And24"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByArticle25",
            "name": "ExemptByArticle25",
            "summary": "Exenta\u0020por\u0020el\u0020art\u00EDculo\u002025",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByArticle25"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\OperationType\u003A\u003AExemptByOther",
            "name": "ExemptByOther",
            "summary": "Exenta\u0020por\u0020otros",
            "url": "classes/josemmo-Verifactu-Models-Records-OperationType.html#enumcase_ExemptByOther"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record",
            "name": "Record",
            "summary": "Base\u0020invoice\u0020record",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003AcalculateHash\u0028\u0029",
            "name": "calculateHash",
            "summary": "Calculate\u0020record\u0020hash",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#method_calculateHash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003AvalidateHash\u0028\u0029",
            "name": "validateHash",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#method_validateHash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003AvalidatePreviousInvoice\u0028\u0029",
            "name": "validatePreviousInvoice",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#method_validatePreviousInvoice"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "Export\u0020record\u0020to\u0020XML",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#method_export"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003A\u0024invoiceId",
            "name": "invoiceId",
            "summary": "ID\u0020de\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#property_invoiceId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003A\u0024previousInvoiceId",
            "name": "previousInvoiceId",
            "summary": "ID\u0020de\u0020factura\u0020del\u0020registro\u0020anterior",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#property_previousInvoiceId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003A\u0024previousHash",
            "name": "previousHash",
            "summary": "Primeros\u002064\u0020caracteres\u0020de\u0020la\u0020huella\u0020o\u0020hash\u0020del\u0020registro\u0020de\u0020facturaci\u00F3n\u0020anterior",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#property_previousHash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003A\u0024hash",
            "name": "hash",
            "summary": "Huella\u0020o\u0020hash\u0020de\u0020cierto\u0020contenido\u0020de\u0020este\u0020registro\u0020de\u0020facturaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#property_hash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\Record\u003A\u003A\u0024hashedAt",
            "name": "hashedAt",
            "summary": "Fecha,\u0020hora\u0020y\u0020huso\u0020horario\u0020de\u0020generaci\u00F3n\u0020del\u0020registro\u0020de\u0020facturaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-Record.html#property_hashedAt"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType",
            "name": "RegimeType",
            "summary": "Claves\u0020de\u0020R\u00E9gimen\u0020Especial\u0020o\u0020Trascendencia\u0020Adicional",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC01",
            "name": "C01",
            "summary": "Operaci\u00F3n\u0020de\u0020r\u00E9gimen\u0020general",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C01"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC02",
            "name": "C02",
            "summary": "Exportaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C02"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC03",
            "name": "C03",
            "summary": "Operaciones\u0020a\u0020las\u0020que\u0020se\u0020aplique\u0020el\u0020r\u00E9gimen\u0020especial\u0020de\u0020bienes\u0020usados,\u0020objetos\u0020de\u0020arte,\u0020antig\u00FCedades\u0020y\u0020objetos\u0020de\u0020colecci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C03"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC04",
            "name": "C04",
            "summary": "R\u00E9gimen\u0020especial\u0020del\u0020oro\u0020de\u0020inversi\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C04"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC05",
            "name": "C05",
            "summary": "R\u00E9gimen\u0020especial\u0020de\u0020las\u0020agencias\u0020de\u0020viajes",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C05"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC06",
            "name": "C06",
            "summary": "R\u00E9gimen\u0020especial\u0020grupo\u0020de\u0020entidades\u0020en\u0020IVA\u0020\u0028Nivel\u0020Avanzado\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C06"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC07",
            "name": "C07",
            "summary": "R\u00E9gimen\u0020especial\u0020del\u0020criterio\u0020de\u0020caja",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C07"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC08",
            "name": "C08",
            "summary": "Operaciones\u0020sujetas\u0020al\u0020IPSI\u0020\/\u0020IGIC\u0020\u0028Impuesto\u0020sobre\u0020la\u0020Producci\u00F3n,\u0020los\u0020Servicios\u0020y\u0020la\u0020Importaci\u00F3n\u0020\/\u0020Impuesto\u0020General\u0020Indirecto\u0020Canario\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C08"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC09",
            "name": "C09",
            "summary": "Facturaci\u00F3n\u0020de\u0020las\u0020prestaciones\u0020de\u0020servicios\u0020de\u0020agencias\u0020de\u0020viaje\u0020que\u0020act\u00FAan\u0020como\u0020mediadoras\u0020en\u0020nombre\u0020y\u0020por\u0020cuenta\u0020ajena\u0020\u0028D.A\u00204\u00AA\u0020RD1619\/2012\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C09"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC10",
            "name": "C10",
            "summary": "Cobros\u0020por\u0020cuenta\u0020de\u0020terceros\u0020de\u0020honorarios\u0020profesionales\u0020o\u0020de\u0020derechos\u0020derivados\u0020de\u0020la\u0020propiedad\u0020industrial,\u0020de\u0020autor\u0020u\u0020otros\u0020por\u0020cuenta\u0020de\u0020sus\u0020socios,\u0020asociados\u0020o\u0020colegiados\u0020efectuados\u0020por\u0020sociedades,\u0020asociaciones,\u0020colegios\u0020profesionales\u0020u\u0020otras\u0020entidades\u0020que\u0020realicen\u0020estas\u0020funciones\u0020de\u0020cobro",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C10"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC11",
            "name": "C11",
            "summary": "Operaciones\u0020de\u0020arrendamiento\u0020de\u0020local\u0020de\u0020negocio",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C11"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC14",
            "name": "C14",
            "summary": "Factura\u0020con\u0020IVA\u0020pendiente\u0020de\u0020devengo\u0020en\u0020certificaciones\u0020de\u0020obra\u0020cuyo\u0020destinatario\u0020sea\u0020una\u0020Administraci\u00F3n\u0020P\u00FAblica",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C14"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC15",
            "name": "C15",
            "summary": "Factura\u0020con\u0020IVA\u0020pendiente\u0020de\u0020devengo\u0020en\u0020operaciones\u0020de\u0020tracto\u0020sucesivo",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C15"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC17",
            "name": "C17",
            "summary": "Operaci\u00F3n\u0020acogida\u0020a\u0020alguno\u0020de\u0020los\u0020reg\u00EDmenes\u0020previstos\u0020en\u0020el\u0020Cap\u00EDtulo\u0020XI\u0020del\u0020T\u00EDtulo\u0020IX\u0020\u0028OSS\u0020e\u0020IOSS\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C17"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC18",
            "name": "C18",
            "summary": "Recargo\u0020de\u0020equivalencia",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C18"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC19",
            "name": "C19",
            "summary": "Operaciones\u0020de\u0020actividades\u0020incluidas\u0020en\u0020el\u0020R\u00E9gimen\u0020Especial\u0020de\u0020Agricultura,\u0020Ganader\u00EDa\u0020y\u0020Pesca\u0020\u0028REAGYP\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C19"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegimeType\u003A\u003AC20",
            "name": "C20",
            "summary": "R\u00E9gimen\u0020simplificado",
            "url": "classes/josemmo-Verifactu-Models-Records-RegimeType.html#enumcase_C20"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord",
            "name": "RegistrationRecord",
            "summary": "Registro\u0020de\u0020alta\u0020de\u0020una\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AcalculateHash\u0028\u0029",
            "name": "calculateHash",
            "summary": "Calculate\u0020record\u0020hash",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_calculateHash"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AvalidatePriorRejection\u0028\u0029",
            "name": "validatePriorRejection",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_validatePriorRejection"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AvalidateTotals\u0028\u0029",
            "name": "validateTotals",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_validateTotals"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AvalidateRecipients\u0028\u0029",
            "name": "validateRecipients",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_validateRecipients"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AvalidateCorrectiveDetails\u0028\u0029",
            "name": "validateCorrectiveDetails",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_validateCorrectiveDetails"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003AvalidateReplacedInvoices\u0028\u0029",
            "name": "validateReplacedInvoices",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#method_validateReplacedInvoices"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024isCorrection",
            "name": "isCorrection",
            "summary": "Indicador\u0020de\u0020subsanaci\u00F3n\u0020de\u0020un\u0020registro\u0020de\u0020facturaci\u00F3n\u0020de\u0020alta\u0020previamente\u0020generado",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_isCorrection"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024isPriorRejection",
            "name": "isPriorRejection",
            "summary": "Indicador\u0020de\u0020rechazo\u0020previo",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_isPriorRejection"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024issuerName",
            "name": "issuerName",
            "summary": "Nombre\u002Draz\u00F3n\u0020social\u0020del\u0020obligado\u0020a\u0020expedir\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_issuerName"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024invoiceType",
            "name": "invoiceType",
            "summary": "Especificaci\u00F3n\u0020del\u0020tipo\u0020de\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_invoiceType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024operationDate",
            "name": "operationDate",
            "summary": "Fecha\u0020en\u0020la\u0020que\u0020se\u0020realiza\u0020la\u0020operaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_operationDate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Descripci\u00F3n\u0020del\u0020objeto\u0020de\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_description"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024recipients",
            "name": "recipients",
            "summary": "Destinatarios\u0020de\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_recipients"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024correctiveType",
            "name": "correctiveType",
            "summary": "Tipo\u0020de\u0020factura\u0020rectificativa",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_correctiveType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024correctedInvoices",
            "name": "correctedInvoices",
            "summary": "Listado\u0020de\u0020facturas\u0020rectificadas",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_correctedInvoices"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024correctedBaseAmount",
            "name": "correctedBaseAmount",
            "summary": "Base\u0020imponible\u0020rectificada\u0020\u0028para\u0020facturas\u0020rectificativas\u0020por\u0020sustituci\u00F3n\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_correctedBaseAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024correctedTaxAmount",
            "name": "correctedTaxAmount",
            "summary": "Cuota\u0020repercutida\u0020o\u0020soportada\u0020rectificada\u0020\u0028para\u0020facturas\u0020rectificativas\u0020por\u0020sustituci\u00F3n\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_correctedTaxAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024replacedInvoices",
            "name": "replacedInvoices",
            "summary": "Listado\u0020de\u0020facturas\u0020sustituidas",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_replacedInvoices"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024breakdown",
            "name": "breakdown",
            "summary": "Desglose\u0020de\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_breakdown"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024totalTaxAmount",
            "name": "totalTaxAmount",
            "summary": "Importe\u0020total\u0020de\u0020la\u0020cuota\u0020\u0028sumatorio\u0020de\u0020la\u0020Cuota\u0020Repercutida\u0020y\u0020Cuota\u0020de\u0020Recargo\u0020de\u0020Equivalencia\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_totalTaxAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\RegistrationRecord\u003A\u003A\u0024totalAmount",
            "name": "totalAmount",
            "summary": "Importe\u0020total\u0020de\u0020la\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Records-RegistrationRecord.html#property_totalAmount"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\TaxType",
            "name": "TaxType",
            "summary": "",
            "url": "classes/josemmo-Verifactu-Models-Records-TaxType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\TaxType\u003A\u003AIVA",
            "name": "IVA",
            "summary": "Impuesto\u0020sobre\u0020el\u0020Valor\u0020A\u00F1adido\u0020\u0028IVA\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-TaxType.html#enumcase_IVA"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\TaxType\u003A\u003AIPSI",
            "name": "IPSI",
            "summary": "Impuesto\u0020sobre\u0020la\u0020Producci\u00F3n,\u0020los\u0020Servicios\u0020y\u0020la\u0020Importaci\u00F3n\u0020\u0028IPSI\u0029\u0020de\u0020Ceuta\u0020y\u0020Melilla",
            "url": "classes/josemmo-Verifactu-Models-Records-TaxType.html#enumcase_IPSI"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\TaxType\u003A\u003AIGIC",
            "name": "IGIC",
            "summary": "Impuesto\u0020General\u0020Indirecto\u0020Canario\u0020\u0028IGIC\u0029",
            "url": "classes/josemmo-Verifactu-Models-Records-TaxType.html#enumcase_IGIC"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records\\TaxType\u003A\u003AOther",
            "name": "Other",
            "summary": "Otros",
            "url": "classes/josemmo-Verifactu-Models-Records-TaxType.html#enumcase_Other"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse",
            "name": "AeatResponse",
            "summary": "Response\u0020from\u0020AEAT\u0020server",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Create\u0020new\u0020instance\u0020from\u0020XML\u0020response",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#method_from"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003A\u0024csv",
            "name": "csv",
            "summary": "CSV\u0020asociado\u0020al\u0020env\u00EDo\u0020generado\u0020por\u0020AEAT",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#property_csv"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003A\u0024submittedAt",
            "name": "submittedAt",
            "summary": "Timestamp\u0020asociado\u0020a\u0020la\u0020remisi\u00F3n\u0020enviada",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#property_submittedAt"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003A\u0024waitSeconds",
            "name": "waitSeconds",
            "summary": "Segundos\u0020de\u0020espera\u0020entre\u0020env\u00EDos",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#property_waitSeconds"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003A\u0024status",
            "name": "status",
            "summary": "Estado\u0020global\u0020del\u0020env\u00EDo",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#property_status"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\AeatResponse\u003A\u003A\u0024items",
            "name": "items",
            "summary": "Estado\u0020detallado\u0020de\u0020cada\u0020l\u00EDnea\u0020del\u0020suministro",
            "url": "classes/josemmo-Verifactu-Models-Responses-AeatResponse.html#property_items"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ItemStatus",
            "name": "ItemStatus",
            "summary": "Estado\u0020del\u0020env\u00EDo\u0020de\u0020un\u0020registro",
            "url": "classes/josemmo-Verifactu-Models-Responses-ItemStatus.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ItemStatus\u003A\u003ACorrect",
            "name": "Correct",
            "summary": "El\u0020registro\u0020de\u0020facturaci\u00F3n\u0020es\u0020totalmente\u0020correcto\u0020y\u0020se\u0020registra\u0020en\u0020el\u0020sistema",
            "url": "classes/josemmo-Verifactu-Models-Responses-ItemStatus.html#enumcase_Correct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ItemStatus\u003A\u003AAcceptedWithErrors",
            "name": "AcceptedWithErrors",
            "summary": "El\u0020registro\u0020de\u0020facturaci\u00F3n\u0020tiene\u0020errores\u0020que\u0020no\u0020provocan\u0020su\u0020rechazo",
            "url": "classes/josemmo-Verifactu-Models-Responses-ItemStatus.html#enumcase_AcceptedWithErrors"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ItemStatus\u003A\u003AIncorrect",
            "name": "Incorrect",
            "summary": "El\u0020registro\u0020de\u0020facturaci\u00F3n\u0020tiene\u0020errores\u0020que\u0020provocan\u0020su\u0020rechazo",
            "url": "classes/josemmo-Verifactu-Models-Responses-ItemStatus.html#enumcase_Incorrect"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\RecordType",
            "name": "RecordType",
            "summary": "Tipo\u0020de\u0020registro",
            "url": "classes/josemmo-Verifactu-Models-Responses-RecordType.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\RecordType\u003A\u003ARegistration",
            "name": "Registration",
            "summary": "Registro",
            "url": "classes/josemmo-Verifactu-Models-Responses-RecordType.html#enumcase_Registration"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\RecordType\u003A\u003ACancellation",
            "name": "Cancellation",
            "summary": "Anulaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Responses-RecordType.html#enumcase_Cancellation"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem",
            "name": "ResponseItem",
            "summary": "Response\u0020for\u0020a\u0020record\u0020submission",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024isCorrection",
            "name": "isCorrection",
            "summary": "Indicador\u0020de\u0020subsanaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_isCorrection"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024invoiceId",
            "name": "invoiceId",
            "summary": "ID\u0020de\u0020factura",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_invoiceId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024recordType",
            "name": "recordType",
            "summary": "Tipo\u0020de\u0020registro\u0020de\u0020operaci\u00F3n",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_recordType"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024status",
            "name": "status",
            "summary": "Estado\u0020del\u0020env\u00EDo\u0020del\u0020registro",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_status"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024errorCode",
            "name": "errorCode",
            "summary": "C\u00F3digo\u0020de\u0020error",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_errorCode"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseItem\u003A\u003A\u0024errorDescription",
            "name": "errorDescription",
            "summary": "Descripci\u00F3n\u0020del\u0020error",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseItem.html#property_errorDescription"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseStatus",
            "name": "ResponseStatus",
            "summary": "Estado\u0020global\u0020del\u0020env\u00EDo",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseStatus.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseStatus\u003A\u003ACorrect",
            "name": "Correct",
            "summary": "Todos\u0020los\u0020registros\u0020de\u0020facturaci\u00F3n\u0020de\u0020la\u0020remisi\u00F3n\u0020tienen\u0020estado\u0020\u0022Correcto\u0022",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseStatus.html#enumcase_Correct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseStatus\u003A\u003APartiallyCorrect",
            "name": "PartiallyCorrect",
            "summary": "Algunos\u0020registros\u0020de\u0020la\u0020remisi\u00F3n\u0020tienen\u0020estado\u0020\u0022Incorrecto\u0022\u0020o\u0020\u0022AceptadoConErrores\u0022",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseStatus.html#enumcase_PartiallyCorrect"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses\\ResponseStatus\u003A\u003AIncorrect",
            "name": "Incorrect",
            "summary": "Todos\u0020los\u0020registros\u0020de\u0020la\u0020remisi\u00F3n\u0020tienen\u0020estado\u0020\u0022Incorrecto\u0022",
            "url": "classes/josemmo-Verifactu-Models-Responses-ResponseStatus.html#enumcase_Incorrect"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient",
            "name": "AeatClient",
            "summary": "Class\u0020to\u0020communicate\u0020with\u0020the\u0020AEAT\u0020web\u0020service\u0020endpoint\u0020for\u0020VERI\u002AFACTU",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Class\u0020constructor",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method___construct"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003AsetCertificate\u0028\u0029",
            "name": "setCertificate",
            "summary": "Set\u0020certificate",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method_setCertificate"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003AsetRepresentative\u0028\u0029",
            "name": "setRepresentative",
            "summary": "Set\u0020representative",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method_setRepresentative"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003AsetProduction\u0028\u0029",
            "name": "setProduction",
            "summary": "Set\u0020production\u0020environment",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method_setProduction"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003AsetEntitySeal\u0028\u0029",
            "name": "setEntitySeal",
            "summary": "Set\u0020entity\u0020seal",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method_setEntitySeal"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\AeatClient\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020invoicing\u0020records",
            "url": "classes/josemmo-Verifactu-Services-AeatClient.html#method_send"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator",
            "name": "QrGenerator",
            "summary": "Service\u0020to\u0020generate\u0020QR\u0020code\u0020URLs.",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator\u003A\u003AsetProduction\u0028\u0029",
            "name": "setProduction",
            "summary": "Set\u0020production\u0020environment",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html#method_setProduction"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator\u003A\u003AsetOnlineMode\u0028\u0029",
            "name": "setOnlineMode",
            "summary": "Set\u0020online\u0020mode",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html#method_setOnlineMode"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator\u003A\u003AfromRegistrationRecord\u0028\u0029",
            "name": "fromRegistrationRecord",
            "summary": "Generate\u0020URL\u0020from\u0020registration\u0020record",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html#method_fromRegistrationRecord"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator\u003A\u003AfromInvoiceId\u0028\u0029",
            "name": "fromInvoiceId",
            "summary": "Generate\u0020URL\u0020from\u0020invoice\u0020ID\u0020and\u0020amount",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html#method_fromInvoiceId"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services\\QrGenerator\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Generate\u0020URL\u0020from\u0020raw\u0020parameters",
            "url": "classes/josemmo-Verifactu-Services-QrGenerator.html#method_from"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/josemmo-verifactu-exceptions.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu",
            "name": "Verifactu",
            "summary": "",
            "url": "namespaces/josemmo-verifactu.html"
        },                {
            "fqsen": "\\josemmo",
            "name": "josemmo",
            "summary": "",
            "url": "namespaces/josemmo.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/josemmo-verifactu-models.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Records",
            "name": "Records",
            "summary": "",
            "url": "namespaces/josemmo-verifactu-models-records.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Models\\Responses",
            "name": "Responses",
            "summary": "",
            "url": "namespaces/josemmo-verifactu-models-responses.html"
        },                {
            "fqsen": "\\josemmo\\Verifactu\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/josemmo-verifactu-services.html"
        }            ]
);
